import { type NextRequest, NextResponse } from "next/server"
import { Pool } from "pg"

export async function POST(request: NextRequest) {
  const startTime = Date.now()
  const logs: string[] = []

  try {
    logs.push(`[${new Date().toISOString()}] Starting direct schema synchronization for all 146 tables...`)

    const localUrl =
      process.env.DATABASE_URL?.includes("localhost") || process.env.DATABASE_URL?.includes("127.0.0.1")
        ? process.env.DATABASE_URL
        : `postgresql://postgres:postgres@127.0.0.1:5432/isp_system`

    logs.push(`Local PostgreSQL URL: ${localUrl}`)

    const localPool = new Pool({ connectionString: localUrl })

    // Test connection
    try {
      await localPool.query("SELECT 1")
      logs.push(`✓ Connected to local PostgreSQL`)
    } catch (connError: any) {
      logs.push(`✗ Failed to connect to local PostgreSQL: ${connError.message}`)
      await localPool.end()
      return NextResponse.json(
        {
          success: false,
          error: "Cannot connect to local PostgreSQL database",
          logs,
        },
        { status: 500 },
      )
    }

    let tablesCreated = 0
    let columnsAdded = 0
    let tablesAlreadySynced = 0
    let errors = 0

    const tableDefinitions: { [key: string]: string[] } = {
      users_sync: [
        "email text",
        "created_at timestamp with time zone",
        "name text",
        "raw_json jsonb",
        "deleted_at timestamp with time zone",
        "updated_at timestamp with time zone",
        "id text PRIMARY KEY",
      ],
      account_balances: [
        "last_payment_date date",
        "last_updated timestamp with time zone",
        "updated_at timestamp without time zone",
        "balance numeric",
        "last_invoice_date date",
        "status character varying",
        "id integer PRIMARY KEY",
        "credit_limit numeric",
        "customer_id integer",
      ],
      admin_logs: [
        "ip_address inet",
        "user_agent text",
        "old_values jsonb",
        "id integer PRIMARY KEY",
        "admin_id integer",
        "action character varying",
        "new_values jsonb",
        "resource_id integer",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "resource_type character varying",
      ],
      automation_workflows: [
        "trigger_conditions jsonb",
        "description text",
        "id integer PRIMARY KEY",
        "is_active boolean DEFAULT true",
        "trigger_type character varying",
        "name character varying",
        "actions jsonb",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
      ],
      backup_access_logs: [
        "id uuid PRIMARY KEY",
        "backup_job_id uuid",
        "created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP",
        "additional_details jsonb",
        "user_id character varying",
        "ip_address inet",
        "user_agent text",
        "action character varying",
        "user_email character varying",
        "success boolean",
        "error_message text",
      ],
      backup_file_inventory: [
        "file_hash character varying",
        "file_type character varying",
        "file_path character varying",
        "last_modified timestamp with time zone",
        "is_encrypted boolean",
        "compression_ratio numeric",
        "backup_job_id uuid",
        "file_size bigint",
        "created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP",
        "id uuid PRIMARY KEY",
      ],
      backup_jobs: [
        "started_at timestamp with time zone",
        "compression_ratio numeric",
        "backup_path character varying",
        "error_message text",
        "storage_location character varying",
        "completed_at timestamp with time zone",
        "cloud_path character varying",
        "includes_files boolean",
        "encryption_used boolean",
        "description text",
        "includes_database boolean",
        "created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP",
        "remote_path character varying",
        "backup_type character varying",
        "checksum character varying",
        "includes_logs boolean",
        "includes_config boolean",
        "updated_at timestamp with time zone",
        "local_path character varying",
        "id uuid PRIMARY KEY",
        "status character varying",
        "file_size character varying",
      ],
      backup_restore_logs: [
        "completed_at timestamp with time zone",
        "restored_components text[]",
        "started_at timestamp with time zone",
        "restore_location character varying",
        "restore_type character varying",
        "error_message text",
        "status character varying",
        "id uuid PRIMARY KEY",
        "created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP",
        "restored_by character varying",
        "backup_job_id uuid",
      ],
      backup_schedules: [
        "is_active boolean DEFAULT true",
        "backup_components jsonb",
        "id uuid PRIMARY KEY",
        "average_duration_minutes numeric",
        "retention_policy jsonb",
        "total_runs integer DEFAULT 0",
        "storage_locations text[]",
        "timezone character varying",
        "cron_expression character varying",
        "last_run timestamp with time zone",
        "created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP",
        "failed_runs integer DEFAULT 0",
        "backup_type character varying",
        "next_run timestamp with time zone",
        "name character varying",
        "updated_at timestamp with time zone",
        "successful_runs integer DEFAULT 0",
      ],
      backup_settings: [
        "maintenance_start time without time zone",
        "backup_customers boolean",
        "backup_network boolean",
        "created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP",
        "remote_password text",
        "enable_scheduled_backups boolean",
        "file_retention_days integer",
        "enable_notifications boolean",
        "enable_integrity_check boolean",
        "remote_path character varying",
        "incremental_time time without time zone",
        "cloud_access_key text",
        "incremental_interval integer",
        "encryption_key text",
        "database_compression character varying",
        "updated_at timestamp with time zone",
        "exclude_patterns text",
        "local_storage_quota integer",
        "enable_local_storage boolean",
        "cloud_secret_key text",
        "full_backup_time time without time zone",
        "enable_cloud_storage boolean",
        "remote_username character varying",
        "cloud_provider character varying",
        "database_retention_days integer",
        "remote_host character varying",
        "full_backup_day character varying",
        "remote_protocol character varying",
        "full_backup_frequency character varying",
        "remote_port integer",
        "backup_logs boolean",
        "enable_encryption boolean",
        "backup_paths text",
        "incremental_frequency character varying",
        "cloud_region character varying",
        "enable_secure_delete boolean",
        "local_cleanup_policy character varying",
        "id uuid PRIMARY KEY",
        "enable_database_backup boolean",
        "maintenance_end time without time zone",
        "backup_settings boolean",
        "enable_file_backup boolean",
        "backup_billing boolean",
        "local_storage_path character varying",
        "cloud_bucket character varying",
        "enable_remote_storage boolean",
        "enable_access_logging boolean",
      ],
      backup_storage_locations: [
        "name character varying",
        "configuration jsonb",
        "test_status character varying",
        "is_primary boolean",
        "id uuid PRIMARY KEY",
        "created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP",
        "is_active boolean DEFAULT true",
        "updated_at timestamp with time zone",
        "total_capacity_gb numeric",
        "used_space_gb numeric",
        "test_message text",
        "last_tested timestamp with time zone",
        "storage_type character varying",
        "available_space_gb numeric",
        "access_credentials jsonb",
        "connection_string text",
      ],
      balance_sheet_view: [
        "revenue_total numeric",
        "equity_total numeric",
        "expense_total numeric",
        "liabilities_total numeric",
        "assets_total numeric",
      ],
      bandwidth_configs: [
        "qos_policy character varying",
        "upload_limit integer",
        "burst_limit integer",
        "id integer PRIMARY KEY",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "download_limit integer",
        "priority integer",
        "device_id integer",
      ],
      bandwidth_patterns: [
        "id integer PRIMARY KEY",
        "average_usage bigint",
        "pattern_date date",
        "peak_usage bigint",
        "hour_of_day integer",
        "day_of_week integer",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
      ],
      bank_transactions: [
        "status character varying",
        "bank_name character varying",
        "transaction_id character varying",
        "updated_at timestamp without time zone",
        "currency character varying",
        "processor_response jsonb",
        "amount numeric",
        "id integer PRIMARY KEY",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "payment_id integer",
        "account_number character varying",
        "bank_reference character varying",
      ],
      billing_cycles: [
        "amount numeric",
        "customer_id integer",
        "cycle_end date",
        "id integer PRIMARY KEY",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "cycle_start date",
        "status character varying",
      ],
      bonus_campaigns: [
        "is_active boolean DEFAULT true",
        "start_date timestamp without time zone",
        "target_audience jsonb",
        "current_participants integer DEFAULT 0",
        "max_participants integer",
        "created_by integer",
        "total_bonus_awarded numeric DEFAULT 0",
        "end_date timestamp without time zone",
        "campaign_type character varying",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "campaign_name character varying",
        "description text",
        "bonus_rules jsonb",
        "id integer PRIMARY KEY",
      ],
      budget_line_items: [
        "id integer PRIMARY KEY",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "quarter_4 numeric",
        "version_id integer",
        "line_item_name character varying",
        "subcategory_id integer",
        "category_id integer",
        "quarter_2 numeric",
        "notes text",
        "budgeted_amount numeric",
        "quarter_1 numeric",
        "quarter_3 numeric",
      ],
      budget_versions: [
        "approved_by integer",
        "version_name character varying",
        "status character varying",
        "budget_year integer",
        "approved_at timestamp without time zone",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "id integer PRIMARY KEY",
      ],
      budgets: [
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "actual_amount numeric",
        "id integer PRIMARY KEY",
        "budget_year integer",
        "budgeted_amount numeric",
        "notes text",
        "updated_at timestamp without time zone",
        "category character varying",
        "budget_period character varying",
      ],
      bus_fare_records: [
        "status character varying",
        "employee_id character varying",
        "to_location character varying",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "from_location character varying",
        "amount numeric",
        "employee_name character varying",
        "travel_date date",
        "id integer PRIMARY KEY",
        "purpose text",
        "approved_by character varying",
        "receipt_number character varying",
      ],
      capacity_alerts: [
        "current_value numeric",
        "severity character varying",
        "status character varying",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "threshold_value numeric",
        "alert_type character varying",
        "id integer PRIMARY KEY",
        "resolved_at timestamp without time zone",
      ],
      capacity_predictions: [
        "prediction_date date",
        "predicted_capacity bigint",
        "id integer PRIMARY KEY",
        "confidence_level numeric",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "model_version character varying",
      ],
      card_transactions: [
        "transaction_id character varying",
        "status character varying",
        "updated_at timestamp without time zone",
        "card_last_four character varying",
        "payment_id integer",
        "currency character varying",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "amount numeric",
        "processor_response jsonb",
        "processor character varying",
        "id integer PRIMARY KEY",
      ],
      cash_flow_categories: [
        "id integer PRIMARY KEY",
        "name character varying",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "category_type character varying",
        "is_inflow boolean",
      ],
      cash_flow_transactions: [
        "transaction_date date",
        "reference_type character varying",
        "description text",
        "id integer PRIMARY KEY",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "category_id integer",
        "amount numeric",
        "bank_account character varying",
        "reference_id integer",
      ],
      cash_transactions: [
        "amount numeric",
        "id integer PRIMARY KEY",
        "status character varying",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "notes text",
        "transaction_id character varying",
        "payment_id integer",
        "received_by character varying",
        "updated_at timestamp without time zone",
      ],
      chart_of_accounts: [
        "account_type character varying",
        "is_active boolean DEFAULT true",
        "description text",
        "id integer PRIMARY KEY",
        "parent_account_id integer",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "account_name character varying",
        "account_code character varying",
      ],
      communication_settings: [
        "id integer PRIMARY KEY",
        "api_key text",
        "sender_id character varying",
        "provider character varying",
        "configuration jsonb",
        "is_active boolean DEFAULT true",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "setting_type character varying",
        "updated_at timestamp without time zone",
      ],
      company_content: [
        "updated_at timestamp with time zone",
        "id integer PRIMARY KEY",
        "created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP",
        "content jsonb",
        "content_type character varying",
      ],
      company_profiles: [
        "phone character varying",
        "industry character varying",
        "logo_url text",
        "updated_at timestamp without time zone",
        "timezone character varying",
        "registration_number character varying",
        "established_date date",
        "id integer PRIMARY KEY",
        "company_prefix character varying",
        "default_language character varying",
        "tax_number character varying",
        "week_start character varying",
        "currency character varying",
        "tax_rate numeric",
        "website character varying",
        "tax_system character varying",
        "time_format character varying",
        "address text",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "email character varying",
        "number_format character varying",
        "company_name character varying",
        "date_format character varying",
        "description text",
      ],
      connection_methods: [
        "config jsonb",
        "name character varying",
        "type character varying",
        "id integer PRIMARY KEY",
        "description text",
        "is_active boolean DEFAULT true",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "updated_at timestamp without time zone",
      ],
      credit_applications: [
        "customer_id integer",
        "amount_applied numeric",
        "id integer PRIMARY KEY",
        "invoice_id integer",
        "adjustment_id integer",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
      ],
      credit_notes: [
        "created_by integer",
        "credit_note_number character varying",
        "notes text",
        "status character varying",
        "customer_id integer",
        "approved_by integer",
        "invoice_id integer",
        "amount numeric",
        "updated_at timestamp without time zone",
        "reason text",
        "id integer PRIMARY KEY",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "approved_at timestamp without time zone",
      ],
      customer_addresses: [
        "postal_code character varying",
        "id integer PRIMARY KEY",
        "address_line2 text",
        "gps_coordinates character varying",
        "state character varying",
        "city character varying",
        "address_line1 text",
        "is_primary boolean DEFAULT false",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "customer_id integer",
        "address_type character varying",
        "country character varying",
      ],
      customer_billing_configurations: [
        "notification_email character varying",
        "late_fee_amount numeric",
        "reminder_days_before integer",
        "updated_at timestamp without time zone",
        "billing_day integer",
        "auto_suspend_on_overdue boolean DEFAULT false",
        "auto_send_invoices boolean DEFAULT true",
        "tax_rate numeric",
        "tax_exempt boolean DEFAULT false",
        "id integer PRIMARY KEY",
        "created_by integer",
        "tax_inclusive boolean DEFAULT false",
        "custom_invoice_template character varying",
        "notification_phone character varying",
        "billing_cycle character varying",
        "grace_period_days integer",
        "credit_limit numeric",
        "pro_rata_enabled boolean DEFAULT false",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "notification_methods jsonb",
        "late_fee_type character varying",
        "auto_generate_invoices boolean DEFAULT true",
        "overdue_threshold_days integer",
        "reminder_days_after integer",
        "payment_terms integer",
        "custom_payment_terms text",
        "auto_send_reminders boolean DEFAULT true",
        "billing_notes text",
        "customer_id integer",
      ],
      customer_categories: [
        "id integer PRIMARY KEY",
        "description text",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "discount_percentage numeric",
        "name character varying",
        "priority_level integer",
      ],
      customer_contacts: [
        "name character varying",
        "relationship character varying",
        "email character varying",
        "is_primary boolean DEFAULT false",
        "phone character varying",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "id integer PRIMARY KEY",
        "contact_type character varying",
        "customer_id integer",
      ],
      customer_document_access_logs: [
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "document_id integer",
        "id integer PRIMARY KEY",
        "action character varying",
        "user_agent text",
        "ip_address inet",
        "user_id integer",
      ],
      customer_document_shares: [
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "id integer PRIMARY KEY",
        "shared_by integer",
        "shared_with_email character varying",
        "access_level character varying",
        "share_token character varying",
        "expires_at timestamp without time zone",
        "is_active boolean DEFAULT true",
        "document_id integer",
      ],
      customer_documents: [
        "document_name character varying",
        "status character varying",
        "file_name character varying",
        "mime_type character varying",
        "updated_at timestamp without time zone",
        "file_size bigint",
        "description text",
        "tags text[]",
        "file_path text",
        "expires_at timestamp without time zone",
        "document_type character varying",
        "uploaded_by integer",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "is_confidential boolean DEFAULT false",
        "parent_document_id integer",
        "id integer PRIMARY KEY",
        "customer_id integer",
        "version integer DEFAULT 1",
      ],
      customer_emergency_contacts: [
        "email character varying",
        "phone character varying",
        "customer_id integer",
        "relationship character varying",
        "name character varying",
        "id integer PRIMARY KEY",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
      ],
      customer_equipment: [
        "issued_date date",
        "updated_at timestamp without time zone",
        "equipment_type character varying",
        "return_reason text",
        "notes text",
        "serial_number character varying",
        "returned_date date",
        "mac_address character varying",
        "inventory_item_id integer",
        "customer_id integer",
        "equipment_name character varying",
        "monthly_cost numeric",
        "assigned_date date",
        "return_condition character varying",
        "ip_address inet",
        "status character varying",
        "verified_serial_match boolean",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "id integer PRIMARY KEY",
        "inventory_serial_number_id integer",
      ],
      customer_notes: [
        "note_type character varying",
        "content text",
        "subject character varying",
        "id integer PRIMARY KEY",
        "created_by integer",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "customer_id integer",
        "is_important boolean DEFAULT false",
      ],
      customer_notifications: [
        "is_read boolean DEFAULT false",
        "id integer PRIMARY KEY",
        "type character varying",
        "message text",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "expires_at timestamp without time zone",
        "title character varying",
        "customer_id integer",
      ],
      customer_payment_accounts: [
        "title character varying",
        "customer_id integer",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "account_details jsonb",
        "id integer PRIMARY KEY",
        "updated_at timestamp without time zone",
        "field_1 character varying",
        "type character varying",
        "is_active boolean DEFAULT true",
      ],
      customer_phone_numbers: [
        "type character varying",
        "is_primary boolean DEFAULT false",
        "phone_number character varying",
        "id integer PRIMARY KEY",
        "customer_id integer",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
      ],
      customer_services: [
        "start_date date",
        "device_id integer",
        "activated_at timestamp without time zone",
        "end_date date",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "customer_id integer",
        "id integer PRIMARY KEY",
        "ip_address inet",
        "config_id integer",
        "status character varying",
        "connection_type character varying",
        "monthly_fee numeric",
        "service_plan_id integer",
        "updated_at timestamp with time zone",
      ],
      customer_statements: [
        "updated_at timestamp without time zone",
        "closing_balance numeric",
        "period_end date",
        "statement_number character varying",
        "viewed_at timestamp without time zone",
        "transaction_count integer DEFAULT 0",
        "customer_id integer",
        "sent_at timestamp without time zone",
        "id integer PRIMARY KEY",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "status character varying",
        "statement_date date",
        "opening_balance numeric",
        "period_start date",
      ],
      customers: [
        "business_name character varying",
        "assigned_staff_id integer",
        "id integer PRIMARY KEY",
        "first_name character varying",
        "city character varying",
        "installation_address text",
        "tax_number character varying",
        "postal_code character varying",
        "business_type character varying",
        "country character varying",
        "preferred_contact_method character varying",
        "email character varying",
        "address text",
        "customer_type character varying",
        "billing_address text",
        "portal_password character varying",
        "account_number character varying",
        "last_name character varying",
        "gps_coordinates character varying",
        "id_number character varying",
        "updated_at timestamp without time zone",
        "portal_username character varying",
        "location_id integer",
        "status character varying",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "phone character varying",
        "referral_source character varying",
        "service_preferences jsonb",
        "state character varying",
      ],
      email_logs: [
        "recipient_email character varying",
        "id integer PRIMARY KEY",
        "sent_at timestamp without time zone",
        "content text",
        "error_message text",
        "subject character varying",
        "bounced_at timestamp without time zone",
        "status character varying",
        "invoice_id integer",
        "opened_at timestamp without time zone",
        "customer_id integer",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "clicked_at timestamp without time zone",
        "email_type character varying",
      ],
      employees: [
        "phone character varying",
        "last_name character varying",
        "first_name character varying",
        "department character varying",
        "employee_id character varying",
        "salary numeric",
        "hire_date date",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "position character varying",
        "status character varying",
        "email character varying",
        "id integer PRIMARY KEY",
      ],
      equipment_returns: [
        "days_in_use integer",
        "verified_serial_match boolean",
        "issued_date date",
        "inventory_serial_number_id integer",
        "inventory_item_id integer",
        "serial_number character varying",
        "return_reason text",
        "customer_id integer",
        "id integer PRIMARY KEY",
        "return_date timestamp without time zone",
        "notes text",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "supplier_id uuid",
        "processed_by integer",
        "return_condition character varying",
        "customer_equipment_id integer",
      ],
      expense_approvals: [
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "comments text",
        "expense_id integer",
        "status character varying",
        "id integer PRIMARY KEY",
        "approver_id integer",
      ],
      expense_categories: [
        "color character varying",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "is_active boolean DEFAULT true",
        "name character varying",
        "budget_amount numeric",
        "updated_at timestamp without time zone",
        "description text",
        "id integer PRIMARY KEY",
      ],
      expense_subcategories: [
        "category_id integer",
        "description text",
        "name character varying",
        "budget_allocation numeric",
        "id integer PRIMARY KEY",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
      ],
      expenses: [
        "status character varying",
        "notes text",
        "approved_by integer",
        "amount numeric",
        "id integer PRIMARY KEY",
        "description text",
        "project_id integer",
        "vendor character varying",
        "tax_amount numeric",
        "category_id integer",
        "recurring_frequency character varying",
        "updated_at timestamp without time zone",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "payment_method character varying",
        "expense_date date",
        "approved_at timestamp without time zone",
        "receipt_url text",
        "is_recurring boolean DEFAULT false",
      ],
      finance_audit_trail: [
        "user_id integer",
        "old_values jsonb",
        "table_name character varying",
        "id integer PRIMARY KEY",
        "record_id integer",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "new_values jsonb",
        "user_agent text",
        "ip_address inet",
        "action character varying",
      ],
      finance_documents: [
        "customer_id integer",
        "notes text",
        "metadata jsonb",
        "total_amount numeric",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "reference_number character varying",
        "amount numeric",
        "type character varying",
        "id integer PRIMARY KEY",
        "due_date date",
        "invoice_date date",
        "created_by integer",
        "invoice_number character varying",
        "description text",
        "status character varying",
        "payment_date date",
        "updated_at timestamp without time zone",
      ],
      financial_adjustments: [
        "approved_by integer",
        "approved_at timestamp without time zone",
        "status character varying",
        "amount numeric",
        "metadata jsonb",
        "reference_number character varying",
        "created_by integer",
        "id integer PRIMARY KEY",
        "customer_id integer",
        "adjustment_type character varying",
        "reason text",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "invoice_id integer",
      ],
      financial_periods: [
        "id integer PRIMARY KEY",
        "start_date date",
        "period_name character varying",
        "is_closed boolean DEFAULT false",
        "end_date date",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "period_type character varying",
      ],
      financial_reports: [
        "report_type character varying",
        "period_start date",
        "period_end date",
        "report_data jsonb",
        "id integer PRIMARY KEY",
        "generated_by integer",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "report_period character varying",
      ],
      fuel_logs: [
        "id integer PRIMARY KEY",
        "location character varying",
        "fuel_type character varying",
        "vehicle_id integer",
        "notes text",
        "log_date date",
        "odometer_reading integer",
        "cost numeric",
        "quantity numeric",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
      ],
      hotspot_sessions: [
        "user_id integer",
        "data_used bigint",
        "hotspot_id integer",
        "end_time timestamp without time zone",
        "id integer PRIMARY KEY",
        "status character varying",
        "start_time timestamp without time zone",
        "ip_address inet",
        "mac_address character varying",
      ],
      hotspot_users: [
        "data_limit integer",
        "time_limit integer",
        "username character varying",
        "password character varying",
        "phone character varying",
        "id integer PRIMARY KEY",
        "email character varying",
        "updated_at timestamp without time zone",
        "hotspot_id integer",
        "status character varying",
        "expiry_date timestamp without time zone",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
      ],
      hotspot_vouchers: [
        "hotspot_id integer",
        "used_count integer DEFAULT 0",
        "status character varying",
        "data_limit integer",
        "id integer PRIMARY KEY",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "max_users integer",
        "time_limit integer",
        "code character varying",
        "expiry_date timestamp without time zone",
      ],
      hotspots: [
        "ssid character varying",
        "device_mac character varying",
        "user_limit integer",
        "device_model character varying",
        "name character varying",
        "id integer PRIMARY KEY",
        "password character varying",
        "status character varying",
        "address text",
        "bandwidth_limit integer",
        "latitude numeric",
        "security_type character varying",
        "location character varying",
        "updated_at timestamp without time zone",
        "ip_address inet",
        "longitude numeric",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
      ],
      infrastructure_investments: [
        "description text",
        "investment_type character varying",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "id integer PRIMARY KEY",
        "status character varying",
        "investment_date date",
        "expected_roi numeric",
        "amount numeric",
      ],
      inventory: [
        "description text",
        "supplier character varying",
        "sku character varying",
        "updated_at timestamp without time zone",
        "unit_cost numeric",
        "stock_quantity integer",
        "category character varying",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "id integer PRIMARY KEY",
        "name character varying",
        "status character varying",
      ],
      inventory_items: [
        "category character varying",
        "specifications text",
        "supplier_id uuid",
        "stock_quantity integer DEFAULT 0",
        "unit_cost numeric",
        "location character varying",
        "updated_at timestamp without time zone",
        "description text",
        "status character varying",
        "sku character varying",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "name character varying",
        "id integer PRIMARY KEY",
      ],
      inventory_serial_numbers: [
        "return_condition character varying",
        "status character varying",
        "serial_number character varying",
        "updated_at timestamp without time zone",
        "received_date date",
        "id integer PRIMARY KEY",
        "assigned_date date",
        "supplier_id uuid",
        "customer_equipment_id integer",
        "returned_date date",
        "notes text",
        "purchase_order_id integer",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "inventory_item_id integer",
      ],
      invoice_items: [
        "unit_price numeric",
        "total_price numeric",
        "invoice_id integer",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "quantity integer",
        "description text",
        "updated_at timestamp without time zone",
        "id integer PRIMARY KEY",
      ],
      invoices: [
        "description text",
        "invoice_number character varying",
        "id integer PRIMARY KEY",
        "customer_id integer",
        "paid_amount numeric DEFAULT 0",
        "amount numeric",
        "due_date date",
        "status character varying",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
      ],
      ip_addresses: [
        "id integer PRIMARY KEY",
        "updated_at timestamp without time zone",
        "notes text",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "assigned_at timestamp without time zone",
        "ip_address inet",
        "released_at timestamp without time zone",
        "subnet_id integer",
        "status character varying",
        "customer_id integer",
      ],
      ip_pools: [
        "id integer PRIMARY KEY",
        "ip_address inet",
        "router_id integer",
        "gateway inet",
        "allocated_at timestamp without time zone",
        "status character varying",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "customer_id integer",
        "subnet_mask character varying",
      ],
      ip_subnets: [
        "updated_at timestamp without time zone",
        "description text",
        "total_ips integer",
        "cidr character varying",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "id bigint PRIMARY KEY",
        "allocation_mode character varying",
        "version character varying",
        "type character varying",
        "status character varying",
        "name character varying",
        "used_ips integer DEFAULT 0",
        "router_id bigint",
      ],
      journal_entries: [
        "entry_number character varying",
        "reference_type character varying",
        "description text",
        "entry_date date",
        "status character varying",
        "total_debit numeric DEFAULT 0",
        "total_credit numeric DEFAULT 0",
        "id integer PRIMARY KEY",
        "created_by integer",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "reference_id integer",
      ],
      journal_entry_lines: [
        "id integer PRIMARY KEY",
        "debit_amount numeric DEFAULT 0",
        "account_id integer",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "credit_amount numeric DEFAULT 0",
        "description text",
        "line_number integer",
        "journal_entry_id integer",
      ],
      knowledge_base: [
        "title character varying",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "id integer PRIMARY KEY",
        "views integer DEFAULT 0",
        "author_id integer",
        "category character varying",
        "tags text[]",
        "content text",
        "updated_at timestamp without time zone",
        "is_published boolean DEFAULT false",
      ],
      locations: [
        "description text",
        "city character varying",
        "name character varying",
        "status character varying",
        "region character varying",
        "updated_at timestamp without time zone",
        "id integer PRIMARY KEY",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "address text",
      ],
      loyalty_redemptions: [
        "description text",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "redemption_value numeric",
        "redemption_type character varying",
        "applied_to_invoice integer",
        "wallet_credit_amount numeric",
        "processed_by integer",
        "id integer PRIMARY KEY",
        "processed_at timestamp without time zone",
        "status character varying",
        "customer_id integer",
        "points_redeemed integer",
        "applied_to_service integer",
      ],
      loyalty_transactions: [
        "source_type character varying",
        "created_by integer",
        "description text",
        "source_id integer",
        "transaction_type character varying",
        "expires_at timestamp without time zone",
        "customer_id integer",
        "points integer",
        "metadata jsonb",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "id integer PRIMARY KEY",
      ],
      maintenance_logs: [
        "service_provider character varying",
        "vehicle_id integer",
        "parts_replaced text",
        "service_type character varying",
        "next_service_date date",
        "description text",
        "odometer_reading integer",
        "id integer PRIMARY KEY",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "service_date date",
        "cost numeric",
      ],
      message_campaigns: [
        "failed_count integer DEFAULT 0",
        "description text",
        "delivered_count integer DEFAULT 0",
        "status character varying",
        "id integer PRIMARY KEY",
        "target_audience jsonb",
        "sent_count integer DEFAULT 0",
        "created_by integer",
        "scheduled_at timestamp without time zone",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "template_id integer",
        "name character varying",
        "total_recipients integer DEFAULT 0",
      ],
      message_templates: [
        "template_type character varying",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "content text",
        "updated_at timestamp without time zone",
        "is_active boolean DEFAULT true",
        "subject character varying",
        "id integer PRIMARY KEY",
        "variables jsonb",
        "name character varying",
      ],
      messages: [
        "id integer PRIMARY KEY",
        "subject character varying",
        "scheduled_at timestamp without time zone",
        "status character varying",
        "delivered_at timestamp without time zone",
        "recipient_type character varying",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "content text",
        "template_id integer",
        "metadata jsonb",
        "sent_at timestamp without time zone",
        "message_type character varying",
        "sender_id integer",
        "recipient_id integer",
      ],
      mpesa_logs: [
        "amount numeric",
        "transaction_id character varying",
        "customer_id integer",
        "checkout_request_id character varying",
        "id integer PRIMARY KEY",
        "merchant_request_id character varying",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "result_desc text",
        "phone_number character varying",
        "result_code integer",
        "transaction_type character varying",
        "invoice_id integer",
        "processed_at timestamp without time zone",
        "raw_response jsonb",
      ],
      network_configurations: [
        "device_id integer",
        "dns2 inet",
        "pppoe_username character varying",
        "dns1 inet",
        "deployed_at timestamp without time zone",
        "id integer PRIMARY KEY",
        "bandwidth_config jsonb",
        "gateway inet",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "pppoe_password character varying",
        "ip_address inet",
        "status character varying",
        "pppoe_enabled boolean DEFAULT false",
      ],
      network_devices: [
        "id integer PRIMARY KEY",
        "type character varying",
        "updated_at timestamp without time zone",
        "location_id integer",
        "configuration jsonb",
        "last_seen timestamp without time zone",
        "ip_address inet",
        "name character varying",
        "location character varying",
        "status character varying",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "mac_address character varying",
      ],
      network_forecasts: [
        "id integer PRIMARY KEY",
        "growth_rate numeric",
        "predicted_users integer",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "forecast_period character varying",
        "predicted_bandwidth bigint",
      ],
      notification_logs: [
        "error_message text",
        "id integer PRIMARY KEY",
        "status character varying",
        "notification_type character varying",
        "updated_at timestamp without time zone",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "channel character varying",
        "recipient_phone character varying",
        "customer_id integer",
        "recipient_email character varying",
        "invoice_id integer",
      ],
      notification_templates: [
        "is_active boolean DEFAULT true",
        "variables jsonb",
        "content text",
        "updated_at timestamp without time zone",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "id integer PRIMARY KEY",
        "subject character varying",
        "template_name character varying",
        "template_type character varying",
      ],
      openvpn_configs: [
        "status character varying",
        "config_content text",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "customer_id integer",
        "expires_at timestamp without time zone",
        "revoked_at timestamp without time zone",
        "router_id integer",
        "id integer PRIMARY KEY",
      ],
      openvpn_logs: [
        "log_timestamp timestamp without time zone",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "bytes_received bigint",
        "id integer PRIMARY KEY",
        "session_duration integer",
        "client_ip inet",
        "bytes_sent bigint",
        "server_ip inet",
        "action character varying",
        "username character varying",
      ],
      payment_applications: [
        "invoice_id integer",
        "amount_applied numeric",
        "payment_id integer",
        "id integer PRIMARY KEY",
        "updated_at timestamp without time zone",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
      ],
      payment_gateway_configs: [
        "api_key text",
        "is_sandbox boolean DEFAULT true",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "id integer PRIMARY KEY",
        "gateway_name character varying",
        "is_active boolean DEFAULT false",
        "secret_key text",
        "updated_at timestamp without time zone",
        "configuration jsonb",
        "webhook_url text",
      ],
      payment_methods: [
        "id integer PRIMARY KEY",
        "configuration jsonb",
        "type character varying",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "is_active boolean DEFAULT true",
        "name character varying",
      ],
      payment_reminders: [
        "amount numeric",
        "customer_id integer",
        "id integer PRIMARY KEY",
        "reminder_type character varying",
        "sent_at timestamp without time zone",
        "status character varying",
        "due_date date",
      ],
      payments: [
        "payment_method character varying",
        "customer_id integer",
        "currency character varying DEFAULT 'KES'",
        "payment_date timestamp without time zone",
        "status character varying",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "transaction_id character varying",
        "id integer PRIMARY KEY",
        "amount numeric",
      ],
      payroll_records: [
        "gross_pay numeric",
        "pay_period_start date",
        "basic_salary numeric",
        "status character varying",
        "deductions numeric DEFAULT 0",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "payment_date date",
        "pay_period_end date",
        "id integer PRIMARY KEY",
        "overtime_hours numeric DEFAULT 0",
        "tax_deduction numeric DEFAULT 0",
        "net_pay numeric",
        "allowances numeric DEFAULT 0",
        "employee_id integer",
        "overtime_rate numeric DEFAULT 0",
      ],
      performance_reviews: [
        "id integer PRIMARY KEY",
        "strengths text",
        "employee_id integer",
        "review_period_end date",
        "reviewer_id integer",
        "development_plan text",
        "areas_for_improvement text",
        "goals_achievement text",
        "status character varying",
        "review_period_start date",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "overall_rating integer",
      ],
      permissions: [
        "permission_key character varying",
        "description text",
        "id integer PRIMARY KEY",
        "module character varying",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "permission_name character varying",
      ],
      portal_sessions: [
        "customer_id integer",
        "id integer PRIMARY KEY",
        "ip_address inet",
        "last_activity timestamp without time zone",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "user_agent text",
        "session_token character varying",
        "expires_at timestamp without time zone",
      ],
      portal_settings: [
        "description text",
        "is_public boolean DEFAULT true",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "setting_value text",
        "setting_type character varying",
        "setting_key character varying",
        "id integer PRIMARY KEY",
        "updated_at timestamp without time zone",
      ],
      purchase_order_items: [
        "inventory_item_id integer",
        "quantity integer",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "id integer PRIMARY KEY",
        "unit_cost numeric",
        "total_cost numeric",
        "purchase_order_id integer",
      ],
      purchase_orders: [
        "updated_at timestamp without time zone",
        "supplier_id uuid",
        "order_number character varying",
        "total_amount numeric",
        "id integer PRIMARY KEY",
        "status character varying",
        "created_by integer",
        "notes text",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
      ],
      radius_logs: [
        "username character varying",
        "acct_session_time integer",
        "nas_port integer",
        "acct_status_type character varying",
        "acct_input_octets bigint",
        "log_timestamp timestamp without time zone",
        "nas_ip inet",
        "acct_session_id character varying",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "acct_terminate_cause character varying",
        "acct_output_octets bigint",
        "framed_ip inet",
        "calling_station_id character varying",
        "id integer PRIMARY KEY",
        "service_type character varying",
        "called_station_id character varying",
      ],
      refunds: [
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "id integer PRIMARY KEY",
        "amount numeric",
        "adjustment_id integer",
        "refund_method character varying",
        "processed_at timestamp without time zone",
        "transaction_reference character varying",
        "updated_at timestamp without time zone",
        "customer_id integer",
        "status character varying",
      ],
      revenue_categories: [
        "description text",
        "is_active boolean DEFAULT true",
        "name character varying",
        "id integer PRIMARY KEY",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "updated_at timestamp without time zone",
      ],
      revenue_streams: [
        "description text",
        "category_id integer",
        "is_recurring boolean DEFAULT false",
        "name character varying",
        "id integer PRIMARY KEY",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
      ],
      role_permissions: [
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "role_id integer",
        "permission_id integer",
        "id integer PRIMARY KEY",
      ],
      roles: [
        "id integer PRIMARY KEY",
        "name character varying",
        "is_system_role boolean DEFAULT false",
        "description text",
        "updated_at timestamp without time zone",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
      ],
      router_logs: [
        "event_type character varying",
        "message text",
        "log_level character varying",
        "log_timestamp timestamp without time zone",
        "id integer PRIMARY KEY",
        "router_id integer",
        "source_module character varying",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "raw_log text",
      ],
      router_performance_history: [
        "uptime bigint",
        "bandwidth_in bigint",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "packet_loss numeric",
        "router_id integer",
        "memory_usage numeric",
        "timestamp timestamp without time zone",
        "latency numeric",
        "cpu_usage numeric",
        "id integer PRIMARY KEY",
        "bandwidth_out bigint",
        "temperature numeric",
      ],
      router_services: [
        "configuration jsonb",
        "router_id integer",
        "updated_at timestamp without time zone",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "is_enabled boolean DEFAULT true",
        "service_type character varying",
        "id integer PRIMARY KEY",
      ],
      router_sync_status: [
        "sync_status character varying",
        "customer_service_id integer",
        "retry_count integer DEFAULT 0",
        "router_id integer",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "last_synced timestamp without time zone",
        "ip_address_id integer",
        "last_checked timestamp without time zone",
        "updated_at timestamp without time zone",
        "id integer PRIMARY KEY",
        "sync_message text",
      ],
      routers: [
        "ssh_port integer DEFAULT 22",
        "memory_usage numeric",
        "sync_error text",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "location_id integer",
        "last_seen timestamp without time zone",
        "type character varying",
        "id bigint PRIMARY KEY",
        "last_sync timestamp without time zone",
        "temperature numeric",
        "username character varying",
        "model character varying",
        "configuration jsonb",
        "hostname character varying",
        "updated_at timestamp without time zone",
        "name character varying",
        "serial_number character varying",
        "password character varying",
        "status character varying",
        "cpu_usage numeric",
        "uptime bigint",
        "connection_type character varying",
        "firmware_version character varying",
        "api_port integer DEFAULT 8728",
        "sync_status character varying",
      ],
      server_configurations: [
        "status character varying",
        "server_type character varying",
        "port integer",
        "last_updated timestamp without time zone",
        "server_name character varying",
        "configuration jsonb",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "id integer PRIMARY KEY",
        "ip_address inet",
      ],
      service_activation_logs: [
        "action character varying",
        "details jsonb",
        "customer_id integer",
        "service_id integer",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "error_message text",
        "status character varying",
        "id integer PRIMARY KEY",
      ],
      service_inventory: [
        "service_id integer",
        "status character varying",
        "assigned_at timestamp without time zone",
        "notes text",
        "id integer PRIMARY KEY",
        "returned_at timestamp without time zone",
        "inventory_id integer",
      ],
      service_plans: [
        "data_limit integer",
        "status character varying",
        "priority_level integer DEFAULT 5",
        "qos_settings jsonb",
        "upload_speed integer",
        "fair_usage_policy text",
        "billing_cycle character varying",
        "id integer PRIMARY KEY",
        "download_speed integer",
        "description text",
        "name character varying",
        "currency character varying DEFAULT 'KES'",
        "features jsonb",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "price numeric",
      ],
      service_requests: [
        "current_service_id integer",
        "requested_service_plan_id integer",
        "id integer PRIMARY KEY",
        "requested_at timestamp without time zone",
        "customer_id integer",
        "processed_at timestamp without time zone",
        "request_type character varying",
        "status character varying",
        "processed_by integer",
        "description text",
        "notes text",
      ],
      sms_logs: [
        "id integer PRIMARY KEY",
        "invoice_id integer",
        "sms_type character varying",
        "delivered_at timestamp without time zone",
        "cost numeric",
        "sent_at timestamp without time zone",
        "status character varying",
        "message_id character varying",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "provider character varying",
        "customer_id integer",
        "failed_at timestamp without time zone",
        "message text",
        "error_message text",
        "recipient_phone character varying",
      ],
      subnets: [
        "gateway inet",
        "router_id integer",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "name character varying",
        "dns_servers text[]",
        "id integer PRIMARY KEY",
        "status character varying",
        "description text",
        "network cidr",
      ],
      supplier_invoice_items: [
        "id integer PRIMARY KEY",
        "unit_cost numeric",
        "description text",
        "invoice_id integer",
        "total_amount numeric",
        "quantity integer",
        "inventory_item_id integer",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
      ],
      supplier_invoices: [
        "invoice_date date",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "id integer PRIMARY KEY",
        "subtotal numeric",
        "supplier_id uuid",
        "paid_amount numeric DEFAULT 0",
        "notes text",
        "due_date date",
        "invoice_number character varying",
        "purchase_order_id integer",
        "updated_at timestamp without time zone",
        "tax_amount numeric",
        "created_by integer",
        "total_amount numeric",
        "status character varying",
        "payment_terms integer DEFAULT 30",
      ],
      suppliers: [
        "tax_id text",
        "payment_terms integer DEFAULT 30",
        "id uuid PRIMARY KEY",
        "contact_name text",
        "address text",
        "company_name text",
        "name text",
        "created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP",
        "is_active boolean DEFAULT true",
        "phone text",
        "email text",
        "updated_at timestamp with time zone",
        "website text",
      ],
      support_tickets: [
        "status character varying",
        "title character varying",
        "ticket_number character varying",
        "resolved_at timestamp without time zone",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "updated_at timestamp without time zone",
        "subject character varying",
        "priority character varying",
        "description text",
        "id integer PRIMARY KEY",
        "assigned_to integer",
        "customer_id integer",
      ],
      sync_jobs: [
        "job_type character varying",
        "error_message text",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "completed_at timestamp without time zone",
        "router_id bigint",
        "id bigint PRIMARY KEY",
        "status character varying",
        "progress integer DEFAULT 0",
        "started_at timestamp without time zone",
        "details jsonb",
      ],
      system_config: [
        "value text",
        "id integer PRIMARY KEY",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "key character varying",
      ],
      system_logs: [
        "user_agent text",
        "updated_at timestamp without time zone",
        "customer_id integer",
        "session_id character varying",
        "timestamp timestamp without time zone",
        "details jsonb",
        "category character varying",
        "level character varying",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "message text",
        "source character varying",
        "ip_address inet",
        "user_id integer",
        "id integer PRIMARY KEY",
      ],
      task_attachments: [
        "id integer PRIMARY KEY",
        "uploaded_by integer",
        "filename character varying",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "file_path text",
        "task_id integer",
        "file_size bigint",
        "mime_type character varying",
      ],
      task_categories: [
        "id integer PRIMARY KEY",
        "description text",
        "color character varying",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "name character varying",
      ],
      task_comments: [
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "id integer PRIMARY KEY",
        "comment text",
        "user_id integer",
        "task_id integer",
      ],
      tasks: [
        "id integer PRIMARY KEY",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "priority character varying",
        "description text",
        "updated_at timestamp without time zone",
        "due_date date",
        "created_by integer",
        "title character varying",
        "status character varying",
        "completed_at timestamp without time zone",
        "assigned_to integer",
      ],
      tax_configurations: [
        "is_active boolean DEFAULT true",
        "id integer PRIMARY KEY",
        "updated_at timestamp without time zone",
        "tax_rate numeric",
        "applies_to character varying",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "tax_name character varying",
        "tax_type character varying",
      ],
      tax_periods: [
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "start_date date",
        "status character varying",
        "period_name character varying",
        "end_date date",
        "id integer PRIMARY KEY",
      ],
      tax_returns: [
        "status character varying",
        "filed_date date",
        "reference_number character varying",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "tax_authority character varying",
        "return_type character varying",
        "penalty_amount numeric DEFAULT 0",
        "taxable_income numeric",
        "tax_due numeric",
        "notes text",
        "id integer PRIMARY KEY",
        "total_revenue numeric",
        "due_date date",
        "total_expenses numeric",
        "period_id integer",
      ],
      trial_balance_view: [
        "credit_total numeric",
        "account_code character varying",
        "account_name character varying",
        "debit_total numeric",
        "balance numeric",
        "account_id integer",
        "account_type character varying",
      ],
      user_activity_logs: [
        "ip_address inet",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "user_type character varying",
        "user_agent text",
        "user_id integer",
        "id integer PRIMARY KEY",
        "session_id character varying",
        "activity character varying",
        "description text",
      ],
      users: [
        "status character varying",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "email character varying",
        "username character varying",
        "role character varying",
        "id integer PRIMARY KEY",
        "password_hash character varying",
      ],
      vehicles: [
        "id integer PRIMARY KEY",
        "purchase_cost numeric",
        "insurance_expiry date",
        "name character varying",
        "updated_at timestamp without time zone",
        "status character varying",
        "last_service date",
        "assigned_to character varying",
        "model character varying",
        "location character varying",
        "mileage integer",
        "purchase_date date",
        "fuel_type character varying",
        "year integer",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "registration character varying",
        "type character varying",
        "license_expiry date",
        "next_service date",
        "fuel_consumption numeric",
      ],
      wallet_balances: [
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "id integer PRIMARY KEY",
        "last_topup_date timestamp without time zone",
        "current_balance numeric DEFAULT 0",
        "updated_at timestamp without time zone",
        "last_transaction_date timestamp without time zone",
        "total_spent numeric DEFAULT 0",
        "customer_id integer",
        "total_bonuses numeric DEFAULT 0",
        "total_topups numeric DEFAULT 0",
      ],
      wallet_bonus_rules: [
        "bonus_percentage numeric",
        "is_active boolean DEFAULT true",
        "max_bonus_amount numeric",
        "topup_min_amount numeric",
        "description text",
        "bonus_fixed_amount numeric",
        "valid_from timestamp without time zone",
        "valid_until timestamp without time zone",
        "max_uses_per_customer integer",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "created_by integer",
        "points_awarded integer DEFAULT 0",
        "updated_at timestamp without time zone",
        "id integer PRIMARY KEY",
        "target_customer_type character varying",
        "points_per_amount numeric DEFAULT 0",
        "rule_name character varying",
      ],
      wallet_transactions: [
        "balance_after numeric",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "source_id integer",
        "description text",
        "transaction_type character varying",
        "id integer PRIMARY KEY",
        "reference_number character varying",
        "balance_before numeric",
        "metadata jsonb",
        "source_type character varying",
        "processed_by integer",
        "customer_id integer",
        "amount numeric",
      ],
      warehouses: [
        "phone character varying",
        "created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP",
        "id bigint PRIMARY KEY",
        "location character varying",
        "contact_person character varying",
        "email character varying",
        "code character varying",
        "name character varying",
        "updated_at timestamp without time zone",
      ],
    }

    const totalTables = Object.keys(tableDefinitions).length
    logs.push(`\n=== Processing ${totalTables} tables ===`)

    // Process each table
    for (const [tableName, columns] of Object.entries(tableDefinitions)) {
      const currentIndex = Object.keys(tableDefinitions).indexOf(tableName) + 1
      logs.push(`\n[${currentIndex}/${totalTables}] Processing table: ${tableName}`)

      try {
        // Check if table exists
        const tableExistsResult = await localPool.query(
          `SELECT EXISTS (
            SELECT FROM information_schema.tables 
            WHERE table_schema = 'public' AND table_name = $1
          )`,
          [tableName],
        )

        const tableExists = tableExistsResult.rows[0].exists

        if (!tableExists) {
          // Create table with all columns
          const createTableSQL = `CREATE TABLE IF NOT EXISTS "${tableName}" (\n  ${columns.join(",\n  ")}\n)`

          await localPool.query(createTableSQL)
          logs.push(`  ✅ Created table: ${tableName} with ${columns.length} columns`)
          tablesCreated++
        } else {
          // Table exists - check for missing columns
          const localColumnsResult = await localPool.query(
            `SELECT column_name
             FROM information_schema.columns
             WHERE table_schema = 'public' AND table_name = $1`,
            [tableName],
          )

          const localColumnNames = new Set(localColumnsResult.rows.map((r: any) => r.column_name))

          // Extract column names from definitions
          const tableColumns = columns
            .map((def) => {
              const match = def.match(/"?(\w+)"?\s/)
              return match ? match[1] : null
            })
            .filter(Boolean)

          const missingColumns = tableColumns.filter((col) => !localColumnNames.has(col))

          if (missingColumns.length > 0) {
            logs.push(`  📝 Found ${missingColumns.length} missing columns`)

            // Add missing columns
            for (const colName of missingColumns) {
              try {
                // Find the column definition
                const colDef = columns.find((def) => def.includes(`"${colName}"`) || def.startsWith(`${colName} `))

                if (colDef) {
                  // Remove PRIMARY KEY constraint when adding to existing table
                  const cleanDef = colDef.replace(/\s+PRIMARY KEY/i, "")

                  const alterSQL = `ALTER TABLE "${tableName}" ADD COLUMN IF NOT EXISTS ${cleanDef}`
                  await localPool.query(alterSQL)

                  logs.push(`    ✓ Added column: ${colName}`)
                  columnsAdded++
                }
              } catch (colError: any) {
                logs.push(`    ✗ Error adding column ${colName}: ${colError.message}`)
                errors++
              }
            }
          } else {
            logs.push(`  ✓ Table already synchronized (${localColumnNames.size} columns)`)
            tablesAlreadySynced++
          }
        }
      } catch (tableError: any) {
        logs.push(`  ✗ Error processing table ${tableName}: ${tableError.message}`)
        errors++
      }
    }

    await localPool.end()

    const duration = ((Date.now() - startTime) / 1000).toFixed(2)

    logs.push(`\n${"=".repeat(60)}`)
    logs.push(`✅ SYNCHRONIZATION COMPLETE`)
    logs.push(`${"=".repeat(60)}`)
    logs.push(`Total tables checked: ${totalTables}`)
    logs.push(`Tables created: ${tablesCreated}`)
    logs.push(`Tables already synced: ${tablesAlreadySynced}`)
    logs.push(`Columns added: ${columnsAdded}`)
    logs.push(`Errors encountered: ${errors}`)
    logs.push(`Duration: ${duration}s`)
    logs.push(`\nYour local PostgreSQL database now has all ${totalTables} tables with matching schemas!`)

    return NextResponse.json({
      success: true,
      totalTables,
      tablesCreated,
      tablesAlreadySynced,
      columnsAdded,
      errors,
      duration: `${duration}s`,
      logs,
    })
  } catch (error: any) {
    logs.push(`\n❌ FATAL ERROR: ${error.message}`)
    logs.push(`Stack trace: ${error.stack}`)

    return NextResponse.json(
      {
        success: false,
        error: error.message,
        stack: error.stack,
        logs,
      },
      { status: 500 },
    )
  }
}
