-- Add missing columns from Splynx CSV export to customers table
-- This migration adds all columns needed for importing customer data from CSV files

ALTER TABLE customers ADD COLUMN IF NOT EXISTS mrr_total DECIMAL(10, 4) DEFAULT 0.0000;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS gdpr_agreed VARCHAR(50);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS prepaid_monthly_costs DECIMAL(10, 4);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS prepaid_expiration_date DATE;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS prepaid_remains_days INTEGER;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS billing_type VARCHAR(50) DEFAULT 'postpaid';
ALTER TABLE customers ADD COLUMN IF NOT EXISTS partner_id INTEGER;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS added_by VARCHAR(100);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS added_by_id INTEGER;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS login VARCHAR(100) UNIQUE;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS category VARCHAR(50);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS password_hash VARCHAR(255);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS billing_email VARCHAR(255);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS street_1 VARCHAR(255);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS street_2 VARCHAR(255);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS zip_code VARCHAR(20);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS date_add TIMESTAMP;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS last_online TIMESTAMP;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS last_update TIMESTAMP;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS daily_prepaid_cost DECIMAL(10, 4) DEFAULT 0.0000;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS conversion_date DATE;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS mpesa_phone_number VARCHAR(50);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS report_first_service_amount DECIMAL(10, 2);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS report_first_service_cancel_date DATE;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS splynx_addon_agents_agent VARCHAR(100);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS splynx_addon_resellers_reseller VARCHAR(100);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS enabled BOOLEAN DEFAULT true;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS type VARCHAR(50) DEFAULT 'person';
ALTER TABLE customers ADD COLUMN IF NOT EXISTS deposit DECIMAL(10, 2) DEFAULT 0.00;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS billing_date INTEGER;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS billing_due INTEGER;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS blocking_period INTEGER;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS grace_period INTEGER;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS make_invoices BOOLEAN DEFAULT true;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS payment_method VARCHAR(50) DEFAULT 'cash';
ALTER TABLE customers ADD COLUMN IF NOT EXISTS min_balance DECIMAL(10, 2) DEFAULT 0.00;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS request_auto_enable BOOLEAN DEFAULT false;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS request_auto_day INTEGER;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS request_auto_period INTEGER;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS reminder_enable BOOLEAN DEFAULT true;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS reminder_day_1 INTEGER;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS reminder_day_2 INTEGER;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS reminder_day_3 INTEGER;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS reminder_payment BOOLEAN DEFAULT false;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS reminder_payment_value DECIMAL(10, 2) DEFAULT 0.00;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS reminder_payment_comment TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS reminder_type INTEGER;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS billing_person VARCHAR(255);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS billing_street_1 VARCHAR(255);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS billing_zip_code VARCHAR(20);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS billing_city VARCHAR(100);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS request_auto_type VARCHAR(50);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS request_auto_next DATE;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS send_finance_notification BOOLEAN DEFAULT true;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS partner_percent DECIMAL(5, 2);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS auto_cap BOOLEAN DEFAULT false;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS auto_cap_tariffs TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS limitation_type VARCHAR(50);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS max_cap_during_month INTEGER;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS transfer_usage_to_new_service BOOLEAN DEFAULT true;

-- Create index on login column for faster lookups
CREATE INDEX IF NOT EXISTS idx_customers_login ON customers(login);
CREATE INDEX IF NOT EXISTS idx_customers_billing_type ON customers(billing_type);
CREATE INDEX IF NOT EXISTS idx_customers_payment_method ON customers(payment_method);
CREATE INDEX IF NOT EXISTS idx_customers_last_online ON customers(last_online);

COMMENT ON COLUMN customers.mrr_total IS 'Monthly Recurring Revenue total';
COMMENT ON COLUMN customers.billing_type IS 'Billing type: prepaid_monthly, prepaid_daily, postpaid, etc.';
COMMENT ON COLUMN customers.login IS 'Customer portal login username (unique)';
COMMENT ON COLUMN customers.password_hash IS 'Hashed portal password';
COMMENT ON COLUMN customers.mpesa_phone_number IS 'M-Pesa mobile money phone number';
COMMENT ON COLUMN customers.enabled IS 'Whether customer account is enabled';
COMMENT ON COLUMN customers.type IS 'Customer type: person or company';
COMMENT ON COLUMN customers.deposit IS 'Security deposit amount';
COMMENT ON COLUMN customers.payment_method IS 'Preferred payment method: cash, mpesa, bank_transfer, etc.';
