#!/bin/bash

echo "=================================================="
echo "FreeRADIUS Clients Configuration Fixer"
echo "=================================================="
echo ""

# Detect network IP
DETECTED_IP=$(ip route get 8.8.8.8 2>/dev/null | grep -oP 'src \K\S+')
echo "✓ Detected Server IP: $DETECTED_IP"

# Get shared secret from database
DB_SECRET=$(sudo -u postgres psql -d isp -t -c "SELECT shared_secret FROM radius_servers WHERE id = 1 LIMIT 1;" 2>/dev/null | tr -d ' ')

if [ -z "$DB_SECRET" ]; then
    echo "⚠️  No shared secret in database, using default 'testing123'"
    DB_SECRET="testing123"
else
    echo "✓ Using shared secret from database"
fi

# Get router IPs from database
ROUTER_IPS=$(sudo -u postgres psql -d isp -t -c "SELECT ip_address FROM network_devices WHERE device_type = 'router' AND status = 'active';" 2>/dev/null | grep -v '^$' | tr -d ' ')

# Backup existing config
CLIENTS_CONF="/etc/freeradius/3.0/clients.conf"
if [ -f "$CLIENTS_CONF" ]; then
    cp "$CLIENTS_CONF" "${CLIENTS_CONF}.backup.$(date +%Y%m%d_%H%M%S)"
    echo "✓ Backed up existing clients.conf"
fi

# Create new clients.conf
echo "✓ Creating new clients.conf with correct IPs..."

cat > "$CLIENTS_CONF" <<EOF
# FreeRADIUS Clients Configuration
# Auto-generated by ISP Management System
# Generated: $(date)

# Allow connections from the server itself
client localhost {
    ipaddr = 127.0.0.1
    secret = $DB_SECRET
    shortname = localhost
    nastype = other
}

# Allow connections from the detected server IP
client server {
    ipaddr = $DETECTED_IP
    secret = $DB_SECRET
    shortname = server
    nastype = other
}

# Allow all IPs on the local network (more permissive)
# This allows routers to connect without individual configuration
client localnet {
    ipaddr = 0.0.0.0/0
    secret = $DB_SECRET
    shortname = all-clients
    nastype = other
}

EOF

# Add individual router entries if available
if [ -n "$ROUTER_IPS" ]; then
    echo "" >> "$CLIENTS_CONF"
    echo "# Individual Router Entries from Database" >> "$CLIENTS_CONF"
    COUNTER=1
    while IFS= read -r ROUTER_IP; do
        if [ -n "$ROUTER_IP" ]; then
            cat >> "$CLIENTS_CONF" <<EOF

client router$COUNTER {
    ipaddr = $ROUTER_IP
    secret = $DB_SECRET
    shortname = router-$ROUTER_IP
    nastype = mikrotik
}
EOF
            echo "  ✓ Added router: $ROUTER_IP"
            COUNTER=$((COUNTER + 1))
        fi
    done <<< "$ROUTER_IPS"
fi

# Set correct permissions
chown freerad:freerad "$CLIENTS_CONF"
chmod 640 "$CLIENTS_CONF"

echo ""
echo "✓ clients.conf updated successfully"
echo ""
echo "New configuration:"
echo "-----------------------------------"
cat "$CLIENTS_CONF"
echo "-----------------------------------"
echo ""

# Test configuration
echo "Testing FreeRADIUS configuration..."
freeradius -CX 2>&1 | head -20

if freeradius -CX > /dev/null 2>&1; then
    echo "✓ Configuration is valid"
    echo ""
    echo "Restarting FreeRADIUS..."
    systemctl restart freeradius
    sleep 2
    
    if systemctl is-active --quiet freeradius; then
        echo "✓ FreeRADIUS started successfully"
        echo ""
        echo "Checking if RADIUS is listening on network..."
        netstat -ulnp | grep 1812
        echo ""
        echo "=================================================="
        echo "SUCCESS! FreeRADIUS is now configured to accept"
        echo "connections from routers on the network."
        echo "=================================================="
    else
        echo "❌ FreeRADIUS failed to start"
        echo "Check logs: journalctl -xeu freeradius.service"
    fi
else
    echo "❌ Configuration has errors"
    echo "Running debug mode..."
    freeradius -X 2>&1 | head -50
fi
